apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "apbsrest.fullname" . }}-minio
  labels:
    app: {{ template "apbsrest.name" . }}
    chart: {{ template "apbsrest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: minio
spec:
#FIXME make this more configurable
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
