apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "apbsrest.fullname" . }}-tesk-proxy
  # name: volcano-jobs
  labels:
    app: {{ template "apbsrest.name" . }}
    chart: {{ template "apbsrest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: tesk-proxy
subjects:
- kind: ServiceAccount
  name: {{ template "apbsrest.fullname" . }}-tesk-proxy
  namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: {{ template "apbsrest.fullname" . }}-tesk-proxy
  # name: volcano-jobs
  apiGroup: rbac.authorization.k8s.io
