apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "apbsrest.fullname" . }}-tesk-proxy
  labels:
    app: {{ template "apbsrest.name" . }}
    chart: {{ template "apbsrest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: tesk-proxy
