apiVersion: v1
kind: Service
metadata:
  name: {{ template "apbsrest.fullname" . }}-task
  labels:
    app: {{ template "apbsrest.name" . }}
    chart: {{ template "apbsrest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: task
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "apbsrest.name" . }}
    release: {{ .Release.Name }}
    service: task
