{{- if .Values.ingress.enabled -}}
{{- $fullName := include "apbsrest.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-viz
  labels:
    app: {{ template "apbsrest.name" . }}
    chart: {{ template "apbsrest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    storage: viz
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /viz/$1
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /viz/(.*)
            backend:
              serviceName: {{ $fullName }}-viz
              servicePort: http
          # - path: /visualize/static/(.*)
          #   backend:
          #     serviceName: {{ $fullName }}-viz
          #     servicePort: http
  {{- end }}
{{- end }}
