name: Build APBS-REST Containers
on: 
  push:
    paths:
      - '.github/workflows/build-test.yaml'
      - 'src/**'

jobs:
  build-images:
    name: Build All Images
    runs-on: ubuntu-latest
    steps:
      # - continue-on-error: false
      - name: Git checkout APBS-REST codebase
        uses: actions/checkout@v1

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.9.2/minikube-linux-amd64
          chmod +x minikube
          sudo mkdir -p /usr/local/bin/
          sudo install minikube /usr/local/bin/

      - name: Verify Minikube Installation and Start Cluster
        run: |
          which minikube
          minikube start --kubernetes-version='v1.15.1' --driver=docker
          minikube status
          minikube addons enable ingress

      - name: Verify and Enter Minikube's Docker Context
        run: |
          minikube docker-env --shell bash
          eval $(minikube -p minikube docker-env --shell bash)

      - name: 'Build Container: ID Service'
        working-directory: ./src/uid
        run: |
          docker build -t apbs-uid .

      # - name: 'Build Container: Storage Service'
      # - name: 'Build Container: Workflow Service'
      # - name: 'Build Container: Task Service'
      # - name: 'Build Container: Proxy Service'
      # - name: 'Build Container: Visualization Service'
      # - name: 'Build Container: Autofill Service'
      # - name: 'Build Container: Uploader'
      # - name: 'Build Container: Downloader'
      # - name: 'Build Container: APBS Runner'
      # - name: 'Build Container: PDB2PQR Runner'