name: Service Integration
on: 
  push:
    paths:
      - '.github/workflows/integration.yaml'
      - 'utilities/wait_for_deployments.py'
      - 'tests/integration/**'
      - 'tests/requirements.txt'
      - 'src/**'
      - 'charts/**'

jobs:
  job1:
    name: Install Dependencies and Run Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout APBS-REST codebase
      uses: actions/checkout@v1

    # - name: Setup Minikube
    #   uses: CodingNagger/minikube-setup-action@v1.0.2
    #   with:
    #     minikube-version: 1.4.0
    #     k8s-version: 1.15.1
    #   id: minikube

    # - name: Launch Minikube
    #   run: eval ${{ steps.minikube.outputs.launcher }}

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v1.0.2
      with:
        minikube version: 'v1.9.2'
        kubernetes version: 'v1.15.1'

    - name: Verify Minikube Installation and Enable Ingress
      run: |
        which minikube
        minikube status
        sudo minikube addons enable ingress

    - name: Download Helm v3
      run: |
        wget https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz
        gunzip helm-v3.0.0-linux-amd64.tar.gz
        tar -xvf helm-v3.0.0-linux-amd64.tar
        mv linux-amd64/ helm-v3

    - name: Verify Helm Installation
      run: |
        which helm
        helm version

    - name: Install APBS-REST via Helm
      run: |
        ./helm-v3/helm install apbs-rest charts/apbs-rest --set ingress.enabled=true,ingress.hosts[0]=apbs.$(minikube ip).xip.io
        # helm install charts/apbs-rest -n apbs-rest --set ingress.enabled=true,ingress.hosts[0]=apbs.$(minikube ip).xip.io

    - name: Wait for deployments
      run: |
        python3 utilities/wait_for_deployments.py 30 20
        kubectl get pods --no-headers=true | awk '/apbs-rest/{print $1}' | xargs kubectl describe pod

    - name: Install PyTest and other Python dependencies
      working-directory: ./tests
      run: |
        python3 -m pip install --upgrade pip
        sudo apt install python3-venv
        python3 -m venv venv
        source venv/bin/activate
        which pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: ./tests/integration
      run: |
        source ../venv/bin/activate
        APBS_HOST=apbs.$(minikube ip).xip.io pytest -n 3
        