name: Service Integration
on: 
  push:
    paths:
      - '.github/workflows/*'
      - 'tests/integration/*'
      - 'tests/requirements.txt'
      - 'src/*'

jobs:
  job1:
    name: Install Software Dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout APBS-REST codebase
      uses: actions/checkout@v1

    - name: Setup Minikube
      uses: CodingNagger/minikube-setup-action@v1.0.2
      with:
        minikube-version: 1.4.0
        k8s-version: 1.16.0
      id: minikube

    - name: Launch Minikube
      run: eval ${{ steps.minikube.outputs.launcher }}

    # TODO: setup using Helm v3 later
    # - name: Setup Helm v2
    #   run: |
    #     kubectl create serviceaccount tiller --namespace kube-system
    #     kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
    #     helm init --service-account=tiller --wait

    - name: Download Helm v3
      run: |
        wget https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz
        gunzip helm-v3.0.0-linux-amd64.tar.gz
        tar -xvf helm-v3.0.0-linux-amd64.tar
        mv linux-amd64/ helm-v3

    - name: Install APBS-REST via Helm
      run: |
        sudo minikube addons enable ingress
        sudo ./helm-v3/helm install apbs-rest charts/apbs-rest --set ingress.enabled=true,ingress.hosts[0]=apbs.$(minikube ip).xip.io
        # helm install charts/apbs-rest -n apbs-rest --set ingress.enabled=true,ingress.hosts[0]=apbs.$(minikube ip).xip.io

    - name: Wait for pods
      uses: CodingNagger/minikube-wait-action@v1.0.1

    - name: Install PyTest and other Python dependencies
      run: |
        cd tests
        python3 -m pip install --upgrade pip
        python3 -m pip install venv
        python3 -m venv venv
        source venv/bin/activate
        which pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        sleep 5
        cd tests/integration
        APBS_HOST=apbs.$(minikube ip).xip.io pytest